"use client";

import { useEffect, useRef, useCallback, useState } from "react";
import { Download, ChevronDown } from "lucide-react";

interface MockupData {
  id: string;
  name: string;
  result_url: string;
  thumbnail_url: string | null;
  metadata: {
    brand_set_id?: string;
    category_slug?: string;
    brandType?: string;
    logoAspect?: string;
    generatedAt?: string;
  } | null;
  mockup_templates: { name: string }[] | null;
}

interface BrandSetViewerProps {
  mockups: MockupData[];
  brandSetId: string;
}

const CATEGORY_LABELS: Record<string, { title: string; description: string }> = {
  packaging: {
    title: "Packaging",
    description: "Your brand on physical products.",
  },
  "business-card": {
    title: "Business Card",
    description: "First impressions that last.",
  },
  "digital-screen": {
    title: "Digital Screen",
    description: "Your identity in the digital world.",
  },
  signage: {
    title: "Signage",
    description: "Bold presence in physical spaces.",
  },
};

export function BrandSetViewer({ mockups, brandSetId }: BrandSetViewerProps) {
  const sectionRefs = useRef<Map<string, HTMLElement>>(new Map());
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  // Intersection Observer for scroll reveal
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("brand-reveal-visible");
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.08, rootMargin: "0px 0px -60px 0px" }
    );

    sectionRefs.current.forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, []);

  const handleDownload = useCallback(async (mockup: MockupData) => {
    setDownloadingId(mockup.id);
    try {
      const resp = await fetch(mockup.result_url);
      const blob = await resp.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${mockup.name.replace(/\s+/g, "-").toLowerCase()}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      // silent
    }
    setDownloadingId(null);
  }, []);

  const hero = mockups[0];
  const rest = mockups.slice(1);

  return (
    <div className="min-h-screen bg-zinc-950">
      {/* Minimal brand mark */}
      <div className="fixed top-6 left-6 z-40">
        <div className="w-8 h-8 bg-white rounded-lg flex items-center justify-center opacity-40">
          <span className="text-zinc-900 font-bold text-xs">M</span>
        </div>
      </div>

      {/* Hero section */}
      <section className="max-w-5xl mx-auto px-6 pt-24 pb-16">
        <div className="text-center mb-20 animate-fade-in">
          <p className="text-[10px] uppercase tracking-[0.3em] text-zinc-600 mb-6">
            Brand Presentation
          </p>
          <h1 className="text-4xl md:text-[3.5rem] font-bold tracking-tight text-white mb-4 leading-[1.08]">
            Brand Visualization
          </h1>
          <p className="text-[14px] text-zinc-500 max-w-md mx-auto">
            A curated brand mockup set, generated by Mockio.
          </p>
          <div className="mt-14 animate-float">
            <ChevronDown size={18} className="mx-auto text-zinc-700" />
          </div>
        </div>

        {/* Hero mockup */}
        <div
          ref={(el) => { if (el) sectionRefs.current.set("hero", el); }}
          className="brand-reveal"
        >
          <div className="group">
            <div className="overflow-hidden rounded-2xl shadow-2xl shadow-black/40">
              <img
                src={hero.result_url}
                alt={hero.name}
                className="w-full h-auto transition-transform duration-700 group-hover:scale-[1.01]"
                loading="eager"
              />
            </div>
            <div className="mt-6 flex items-center justify-between">
              <p className="text-[11px] uppercase tracking-[0.2em] text-zinc-600">
                {getLabel(hero).title}
              </p>
              <button
                onClick={() => handleDownload(hero)}
                disabled={downloadingId === hero.id}
                className="flex items-center gap-1.5 text-[12px] text-zinc-600 hover:text-white transition-colors"
              >
                <Download size={12} />
                {downloadingId === hero.id ? "Saving..." : "Download"}
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Rest of mockups */}
      {rest.map((mockup, i) => {
        const label = getLabel(mockup);
        return (
          <section
            key={mockup.id}
            ref={(el) => { if (el) sectionRefs.current.set(mockup.id, el); }}
            className="brand-reveal max-w-5xl mx-auto px-6 py-20"
          >
            <div className="group">
              <div className="overflow-hidden rounded-2xl shadow-xl shadow-black/30">
                <img
                  src={mockup.result_url}
                  alt={mockup.name}
                  className="w-full h-auto transition-transform duration-700 group-hover:scale-[1.01]"
                  loading="lazy"
                />
              </div>
              <div className="mt-6 flex items-center justify-between">
                <div>
                  <p className="text-[11px] uppercase tracking-[0.2em] text-zinc-600">
                    {label.title}
                  </p>
                  <p className="text-[12px] text-zinc-700 mt-0.5">
                    {label.description}
                  </p>
                </div>
                <button
                  onClick={() => handleDownload(mockup)}
                  disabled={downloadingId === mockup.id}
                  className="flex items-center gap-1.5 text-[12px] text-zinc-600 hover:text-white transition-colors"
                >
                  <Download size={12} />
                  {downloadingId === mockup.id ? "Saving..." : "Download"}
                </button>
              </div>
            </div>
            {i < rest.length - 1 && (
              <div className="mt-20">
                <div className="h-px bg-zinc-800/30" />
              </div>
            )}
          </section>
        );
      })}

      {/* Footer */}
      <footer className="max-w-5xl mx-auto px-6 py-20 text-center">
        <div className="h-px bg-zinc-800/30 mb-12" />
        <p className="text-[11px] text-zinc-700 tracking-wide">
          {mockups.length} mockups · Generated by Mockio
        </p>
      </footer>
    </div>
  );
}

function getLabel(mockup: MockupData) {
  const slug = mockup.metadata?.category_slug || "";
  return (
    CATEGORY_LABELS[slug] || {
      title: mockup.name.replace("Brand Set – ", ""),
      description: "Part of your brand story.",
    }
  );
}
